# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: beb76803edc081ba6eb72925bb6e277c2e49fe577f2c2ae9a81272478e3d6549e4962255e08951835beb1d8f21c0f7f7acf26e8150d9580fccfdbea1f235ed03

test:
  secret_key_base: 8fa5ccee5dff1127237554e179b3c07c38f73898626e97a8cb9581fcc2911bc727dd9e0f46aed4d9ad979c9e97819dc70dfd1094aae89a8e45f5f73369caa655

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
